- added manual aws filesystem volume provisioning with external volume, created manually from AWS console (with volume id) - restricted kubernetes cluster availability zone only to "eu-central-1a" so tha cluster worker node will be able to mount manually created volumes (all volumes are created in availability zone "eu-central-1a"

diff --git a/k8s/moviebets-mongodb.yml b/k8s/moviebets-mongodb.yml
--- a/k8s/moviebets-mongodb.yml
+++ b/k8s/moviebets-mongodb.yml
@@ -4,13 +4,16 @@ metadata:
   name: moviebets-mongodb-pv
 spec:
   capacity:
-    storage: 10Gi  # Adjust storage size as needed
+    storage: 10Gi
+  volumeMode: Filesystem
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
-  storageClassName: manual  # Use manual storage class for explicit PV binding
-  hostPath:
-    path: "/mnt/data/mongodb"  # This path is on the host node
+  storageClassName: manual
+  awsElasticBlockStore:
+    volumeID: vol-0c320654b03ec1d95
+    fsType: ext4
+
 ---
 apiVersion: v1
 kind: PersistentVolumeClaim
@@ -19,10 +22,10 @@ metadata:
 spec:
   accessModes:
     - ReadWriteOnce
+  storageClassName: manual
   resources:
     requests:
       storage: 10Gi
-  storageClassName: manual  # Match the manual storage class with the PV
 
 ---
 apiVersion: apps/v1
@@ -39,16 +42,53 @@ spec:
       labels:
         app: moviebets-mongodb
     spec:
+      initContainers:
+        - name: format-and-resize-filesystem
+          image: alpine
+          command:
+            - sh
+            - -c
+            - |
+              apk add --no-cache e2fsprogs && \
+              if ! blkid /data/db >/dev/null 2>&1; then
+                echo "Filesystem not found, formatting..."
+                mkfs.ext4 /data/db || echo "Formatting failed"
+              else
+                echo "Filesystem exists, skipping format"
+              fi && \
+              resize2fs /data/db || echo "Resize failed or not needed"
+          volumeMounts:
+            - name: mongodb-storage
+              mountPath: /data/db
       containers:
-          - name: moviebets-mongodb
-            image: mongo:8.0.5
-            imagePullPolicy: IfNotPresent
-            ports:
-              - containerPort: 27017
-            volumeMounts:
-              - name: mongodb-storage
-                mountPath: /data/db
-            resources: {}
+        - name: moviebets-mongodb
+          image: mongo:8.0.5
+          imagePullPolicy: IfNotPresent
+          ports:
+            - containerPort: 27017
+          volumeMounts:
+            - name: mongodb-storage
+              mountPath: /data/db
+          resources: {}
+          readinessProbe:
+            exec:
+              command:
+                - mongo
+                - --eval
+                - "db.adminCommand('ping')"
+            initialDelaySeconds: 15
+            timeoutSeconds: 5
+            periodSeconds: 10
+
+          livenessProbe:
+            exec:
+              command:
+                - mongo
+                - --eval
+                - "db.adminCommand('ping')"
+            initialDelaySeconds: 30
+            timeoutSeconds: 5
+            periodSeconds: 20
       restartPolicy: Always
       volumes:
         - name: mongodb-storage
diff --git a/k8s/moviebets-postgres.yml b/k8s/moviebets-postgres.yml
--- a/k8s/moviebets-postgres.yml
+++ b/k8s/moviebets-postgres.yml
@@ -4,13 +4,16 @@ metadata:
   name: moviebets-postgres-pv
 spec:
   capacity:
-    storage: 10Gi  # Adjust storage size as needed
+    storage: 10Gi
+  volumeMode: Filesystem
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
-  storageClassName: manual  # Use manual storage class for explicit PV binding
-  hostPath:
-    path: "/mnt/data/postgresql"  # This path is on the host node
+  storageClassName: manual
+  awsElasticBlockStore:
+    volumeID: vol-06b9132eaa8482374
+    fsType: ext4
+
 ---
 apiVersion: v1
 kind: PersistentVolumeClaim
@@ -19,10 +22,10 @@ metadata:
 spec:
   accessModes:
     - ReadWriteOnce
+  storageClassName: manual
   resources:
     requests:
       storage: 10Gi
-  storageClassName: manual  # Match the manual storage class with the PV
 
 ---
 apiVersion: apps/v1
@@ -41,12 +44,33 @@ spec:
     spec:
       imagePullSecrets:
         - name: image-pull-secret
+      initContainers:
+        - name: format-and-resize-filesystem
+          image: alpine
+          command:
+            - sh
+            - -c
+            - |
+              apk add --no-cache e2fsprogs && \
+              # Check if /var/lib/postgresql/data is already formatted
+              if ! blkid /var/lib/postgresql/data >/dev/null 2>&1; then
+                echo "Filesystem not found, formatting..."
+                mkfs.ext4 /var/lib/postgresql/data || echo "Formatting failed"
+              else
+                echo "Filesystem exists, skipping format"
+              fi && \
+              resize2fs /var/lib/postgresql/data || echo "Resize failed or not needed"
+          volumeMounts:
+            - name: postgres-storage
+              mountPath: /var/lib/postgresql/data
       containers:
         - env:
             - name: POSTGRES_USER
               value: postgres
             - name: POSTGRES_PASSWORD
               value: dbpass
+            - name: PGDATA
+              value: "/var/lib/postgresql/data/pgdata"
             - name: PGTZ
               value: "Europe/Amsterdam"
             - name: BET_DB_USER
@@ -67,7 +91,7 @@ spec:
               value: "dbpass"
             - name: MARKET_DB_NAME
               value: "marketdb"
-          image: $CONTAINER_REGISTRY/moviebets-postgres:17.2
+          image: ghcr.io/skyglass/movie-bets/moviebets-postgres:17.2
           name: moviebets-postgres
           imagePullPolicy: IfNotPresent
           ports:
@@ -76,6 +100,26 @@ spec:
             - name: postgres-storage
               mountPath: /var/lib/postgresql/data  # Default data path for PostgreSQL
           resources: {}
+          readinessProbe:
+            exec:
+              command:
+                - pg_isready
+                - -U
+                - postgres
+            initialDelaySeconds: 10
+            periodSeconds: 10
+            timeoutSeconds: 5
+            failureThreshold: 6
+          livenessProbe:
+            exec:
+              command:
+                - pg_isready
+                - -U
+                - postgres
+            initialDelaySeconds: 30
+            periodSeconds: 20
+            timeoutSeconds: 5
+            failureThreshold: 3
       restartPolicy: Always
       volumes:
         - name: postgres-storage
